name: habit_tracker
description: "DailyHabit - build your habit, daily."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/images/app_icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
